<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.11" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="9.0.11" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\QualityLock.Application\QualityLock.Application.csproj" />
    <ProjectReference Include="..\QualityLock.Infrastructure\QualityLock.Infrastructure.csproj" />
    <ProjectReference Include="..\QualityLock.Shared\QualityLock.Shared.csproj" />
  </ItemGroup>

</Project>
